name: create azure image by packer

on: [push]

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main

      - name: Run `packer validate`
        run: "packer validate --var client_id=${{ secrets.AZURE_CLIENT_ID}} --var client_secret=${{ secrets.AZURE_CLIENT_SECRET}} --var subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }} --var tenant_id=${{ secrets.AZURE_TENANT_ID }} ./azure-ubuntu.pkr.hcl"
