name: create azure image by packer

on: [push]

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: echo hello!

  show:
    runs-on: ubuntu-latest
    steps:
      - name: show secret
        run: echo ${{ secrets.AZURE_CLIENT_ID }}